// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCi4ze2jfENUkUfifg58wUrBDIX2dr-No',
    appId: '1:901508032037:web:f0fe422c31db3b59d9c1cc',
    messagingSenderId: '901508032037',
    projectId: 'shopping-app-26a60',
    authDomain: 'shopping-app-26a60.firebaseapp.com',
    storageBucket: 'shopping-app-26a60.firebasestorage.app',
    measurementId: 'G-JM1EWYN926',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCImt_LOEGRy5LeYktg65kFBfb6n57r9ps',
    appId: '1:901508032037:android:cdcf96c23fdf27e6d9c1cc',
    messagingSenderId: '901508032037',
    projectId: 'shopping-app-26a60',
    storageBucket: 'shopping-app-26a60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYrkaCCPg1LhdCxjWE90XEShEm8PVMa3s',
    appId: '1:901508032037:ios:d12bc3aef87ec883d9c1cc',
    messagingSenderId: '901508032037',
    projectId: 'shopping-app-26a60',
    storageBucket: 'shopping-app-26a60.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );
}
